version: '3.8'

services:
  firefly-ai-categorizer-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: firefly-ai-categorizer-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9229:9229"  # Node.js debugging port
    environment:
      # Required environment variables
      - FIREFLY_URL=${FIREFLY_URL}
      - FIREFLY_PERSONAL_TOKEN=${FIREFLY_PERSONAL_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Development environment variables
      - NODE_ENV=development
      - ENABLE_UI=${ENABLE_UI:-true}
      - PORT=${PORT:-3000}
      - FIREFLY_TAG=${FIREFLY_TAG:-AI categorized}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - DEBUG=firefly:*
    
    # Volume mounts for development (enable hot reloading)
    volumes:
      - .:/app
      - /app/node_modules  # Anonymous volume to preserve node_modules
      - ./logs:/app/logs
    
    # Health check (more lenient for development)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 60s
    
    # Networks
    networks:
      - firefly-dev-network
    
    # Development command with nodemon for hot reloading
    command: ["npm", "run", "dev"]
    
    # Enable debugging
    stdin_open: true
    tty: true

networks:
  firefly-dev-network:
    driver: bridge
    name: firefly-ai-dev-network 